# Generated by Django 5.2.6 on 2025-10-22 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cipher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cipher_type', models.CharField(choices=[('RSA', 'rsa'), ('KUZNECHIK', 'kuznechik')], max_length=16)),
                ('text', models.TextField()),
                ('ciphered', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
