# Generated by Django 5.2.7 on 2025-10-23 21:17

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cipher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret_app',
            field=models.CharField(default=pyotp.random_base32, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret_email',
            field=models.CharField(default=pyotp.random_base32, max_length=64),
        ),
    ]
